apiVersion: v1
kind: Pod
metadata:
  annotations:
    field.cattle.io/ports: '[[{"containerPort":9001,"dnsName":"cnn-sprout-server-dev-nodeport","kind":"NodePort","name":"9001tcp01","protocol":"TCP","sourcePort":0}]]'
  creationTimestamp: 2019-04-15T18:16:32Z
  generateName: cnn-sprout-server-dev-684b6659fb-
  labels:
    pod-template-hash: "2406221596"
    workload.user.cattle.io/workloadselector: deployment-whiteboard-nonprod-cnn-sprout-server-dev
  name: cnn-sprout-server-dev-684b6659fb-bcs4g
  namespace: whiteboard-nonprod
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cnn-sprout-server-dev-684b6659fb
    uid: 989ebfeb-5faa-11e9-aab2-02b0313e543a
  resourceVersion: "1527918"
  selfLink: /api/v1/namespaces/whiteboard-nonprod/pods/cnn-sprout-server-dev-684b6659fb-bcs4g
  uid: 98a01f59-5faa-11e9-aab2-02b0313e543a
spec:
  containers:
  - env:
    - name: AUTH_API_URL
      value: https://firefly-auth.api.cnn.io/virtuoso-auth-api/v1/login
    - name: DEBUG
      value: app:mongoose,app:lib:authUsers-api
    - name: ENVIRONMENT
      value: dev
    - name: HEALTHCHECK
      value: /hc
    - name: MONGODB_CONNECT_STRING
      value: mongodb://cnn-sprout-dev:ewABqY$Vx4T7@ds137801.mlab.com:37801/cnn-sprout-dev
    - name: NODE_ENV
      value: dev
    - name: PORT
      value: "9001"
    image: quay.io/turner/jth-cnn-sprout-server:2019-04-13T00.04.33-ip-10-63-198-234.HEAD.ed3ce0a
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /hc
        port: 9001
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    name: cnn-sprout-server-dev
    ports:
    - containerPort: 9001
      name: 9001tcp01
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /hc
        port: 9001
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 2
      successThreshold: 2
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 15m
        memory: 64Mi
    securityContext:
      capabilities: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jz8qm
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: quay
  nodeName: ip-192-168-18-233.ec2.internal
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jz8qm
    secret:
      defaultMode: 420
      secretName: default-token-jz8qm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-04-15T18:16:32Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-04-15T18:16:59Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-04-15T18:16:32Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://621358c8b7fe45b129dde38b47c7b2feff6b40a9316020244c3883c78cefb2bf
    image: quay.io/turner/jth-cnn-sprout-server:2019-04-13T00.04.33-ip-10-63-198-234.HEAD.ed3ce0a
    imageID: docker-pullable://quay.io/turner/jth-cnn-sprout-server@sha256:cd82c06b52c15cdc4f52f22321158964fac8ddb43c3297af80980ae479cbe83a
    lastState: {}
    name: cnn-sprout-server-dev
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-04-15T18:16:46Z
  hostIP: 192.168.18.233
  phase: Running
  podIP: 192.168.58.215
  qosClass: Burstable
  startTime: 2019-04-15T18:16:32Z

